version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zemdocs_postgres_dev
    environment:
      POSTGRES_DB: zemdocs_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zemdocs_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zemdocs_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - zemdocs_dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-13T07-53-03Z-cpuv1
    container_name: zemdocs_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - zemdocs_dev_network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # DBGate for database management
  dbgate:
    image: dbgate/dbgate:latest
    container_name: zemdocs-dbgate-dev
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      CONNECTIONS: con1
      LABEL_con1: ZemDocs PostgreSQL
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: postgres
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
      DATABASE_con1: zemdocs_dev
    ports:
      - "3002:3000"
    networks:
      - zemdocs_dev_network
    volumes:
      - dbgate_data:/root/.dbgate

volumes:
  postgres_dev_data:
  redis_dev_data:
  minio_data:
  dbgate_data:

networks:
  zemdocs_dev_network:
    driver: bridge
